# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 20:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s+]+$', 'Car model must have only alphanumeric characters')], verbose_name='Car model')),
                ('color', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s+]+$', 'Car color must have only alphabetical characters')], verbose_name='Car color')),
                ('license_plate', models.CharField(help_text='Do not use hyphen (-). Use only letters and numbers. Ex.: JHG1234', max_length=7, validators=[django.core.validators.RegexValidator('^([A-Z]{3})([0-9]{4})$', 'License plate must contain 3 letters and 4 numbers')], verbose_name='License Plate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
