# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 00:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Do not use hyphen (-). Use only letters and numbers. Ex.: JHG1234', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^([A-Z]{3})([0-9]{4})$', 'License plate must contain 3 letters and 4 numbers')], verbose_name='License Plate'),
        ),
    ]
